---
driver:
  name: vagrant
  customize:
    memory: 1024
  network:
    - ["private_network", { type: "dhcp" }]

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  requirements_path: requirements.yml
  require_pip: true
  require_ansible_repo: false
  ansible_version:  2.3.0.0
  ansible_verbose:  false
  ansible_verbosity: 2
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  ignore_paths_from_root:
    - .kitchen

platforms:
  - name: ubuntu-14.04
    driver:
      box: ubuntu/trusty64
  - name: ubuntu-16.04
    driver:
      box: ubuntu/xenial64
  - name: centos-7.2
    driver:
      box: bento/centos-7.2

suites:
  - name: node0
    driver:
      network:
        - ["private_network", { ip: "172.29.129.110" }]
  - name: node1
    driver:
      network:
        - ["private_network", { ip: "172.29.129.120" }]
